### PR TITLE
[WIP] More Documentation for Next Release

### PR DESCRIPTION
**Pull request by bganglia**
List given by @naustica in #23:

cache
- [x] basic explanation
- [ ] polished

data format 
- [x] basic explanation
- [ ] polished

error handling
 - [x] basic explanation
- [ ] polished

other
- [ ] general check
(+) update changelog

### CODE REVIEW

**Comment by bganglia** [comment]
My goal for the data format description is a more concise version of the [official explanation](http://unpaywall.org/data-format), which we can also link to. 

I would also like to provide specific examples of what each field might look like.

**Comment by naustica** [comment]
@bganglia Can you describe the timeout parameter in the docs in more detail? Because, I think it is not clear at first sight.

**Comment by bganglia** [comment]
@naustica Good suggestion. Should I add an example, maybe with time.sleep() to show the difference?

Also, do you think it is better to describe the Unpaywall schema using a table, or just bullet points?

I started reformatting the table (split into two now, one for DOI Objects and one for OA Location objects), but I have not pushed them yet because they have invalid sphinx syntax (lines are not even)

**Comment by naustica** [comment]
@bganglia Yeah, why not.

I prefer a table. When you think its too messy, you can also use bullet points.

**Comment by naustica** [comment]
@bganglia When do you think you will probably be finished?

**Comment by bganglia** [comment]
@naustica My plan is to finish tonight. Is 19:00 UTC a reasonable time?

**Comment by naustica** [comment]
@bganglia perfect

**Comment by bganglia** [comment]
@naustica Let me know if it looks like anything needs changing, especially in the data format section. If it looks OK I will mark off the "polished" check marks.

I linked to the official documentation in the data format section because that part is essentially a paraphrase of it.

**Comment by naustica** [comment]
@bganglia Had you already looked through my text?

**Comment by naustica** [comment]
@bganglia Looks good! 
Just change " to ' in the cache code examples. Also, there might be an unfinished sentence at the end of the cache text.

**Comment by bganglia** [comment]
@naustica I glanced through it a couple of days ago, but I was not really looking for mistakes if that is what you mean. It looked pretty professional to me. I can look through it more carefully

**Comment by bganglia** [comment]
@naustica Thanks, let me change those things.

**Comment by naustica** [comment]
@bganglia If you see no mistakes in my text I would merge it

**Comment by bganglia** [comment]
@naustica I just took another look through the text and tried some of the code examples, and I couldn't find any problems.

**Comment by naustica** [comment]
@bganglia great! I would prepare the package update then.

**Pull request merged**
