### PR TITLE
Readthedocs site

### LINKED ISSUE #23: Readthedocs site for first release
It would probably be enough just to use autodoc to get started

### PR DESCRIPTION
**Pull request by bganglia**
PR to replace unpaywallpython readthedocs site with unpywall readthedocs site.

For some reason, the "latest" build of the docs always refers to the older unpaywallpython docs. I am hoping that if we merge this into master, it will refer to the new unpywall docs.

This should close #23, but more documentation could also be added later.

### CODE REVIEW

**Comment by naustica** [comment]
I didnt know that you can host documentation for free. Thats awesome! 

Can you rename the source folder to docs?

I like the style of the flask documentation a lot. https://flask.palletsprojects.com/en/1.1.x/ I think it is the Alabaster theme. What do you think about this?

**Comment by bganglia** [comment]
I forgot to add the links to the current and deprecated documentation:
Current https://unpywall.readthedocs.io/en/readthedocs/
Deprecated https://unpywall.readthedocs.io/en/latest/

It looks like the alabaster theme is the default, which is nice. The sidebar looks a little different, but maybe there is a way to tweak it.

Currently the documentation is a little bare, so that is another thing to work on.

**Comment by naustica** [comment]
Great! 
I replaced the base branch master with develop.
Is there a reason, why only the unypwall class is shown in the docs?

**Comment by naustica** [comment]
Apparently, there is a problem with displaying Raise and Return values in the documentation. Maybe the docstring format is not set up correctly.

**Comment by naustica** [comment]
@bganglia I think this extension fits our needs (https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html).

**Comment by bganglia** [comment]
@naustica Great, I will try adding it

**Comment by bganglia** [comment]
@naustica 
It looks better now:
https://unpywall.readthedocs.io/en/readthedocs/

**Comment by naustica** [comment]
@bganglia Great! You can merge it if you want.

**Comment by naustica** [comment]
I would like to have a better side navigation, but I can do that later.

**Comment by naustica** [comment]
@bganglia Also, can you add type hinting to the caching class?

**Comment by bganglia** [comment]
@naustica Yes, that sounds like a good idea

**Comment by naustica** [comment]
@bganglia the readthedocs webhook needs to be updated. Also, I have no access to the unpywall project on rtd. Can you fix that?

**Comment by bganglia** [comment]
@naustica I think you have been added now. Let me know if you are able to get in

**Comment by naustica** [comment]
@bganglia Thanks! It works now.

What is the difference between the latest and readthedocs build?

**Comment by bganglia** [comment]
@naustica Latest is built off the master branch. Right now there is no documentation there, so it still has the unpaywallpython docs. That is why I am thinking that we should maybe merge this into master instead of develop, so that we can replace the old docs with the new docs

**Comment by bganglia** [comment]
@naustica Actually the unpaywallpython docs are gone now. It just has a blank starting page. But the reason is still that there is no documentation to build in the master branch

**Comment by naustica** [comment]
Ah ok. 
I updated the appearance of the documentation https://unpywall.readthedocs.io/en/readthedocs/ btw.

I would add text next.

I dont think that anyone is currently looking at the documentation, so there is no need to merge it into master, but of course we can do that.

**Comment by bganglia** [comment]
@naustica In that case we could also wait for the next release.

Also, yes, the navigation and organization look awesome. Thank you

**Comment by naustica** [comment]
@bganglia I will also merge this branch into develop.

**Pull request merged**
